#! python3

import os
import datetime

os.chdir(r'C:\...\...\...')
time = datetime.datetime.today()
startup = time.strftime("%Y-%m-%d %H:%M:%S")

logFile = open('Windows timelog.txt', 'a')

logFile.write('Start ' + startup +'\n')

logFile.close()
